# Generated by Django 3.1.7 on 2021-08-31 21:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessPiece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('KI', 'King'), ('R', 'Rook'), ('B', 'Bishop'), ('Q', 'Queen'), ('KN', 'Knight'), ('P', 'Pawn')], max_length=150, verbose_name='tipo')),
                ('color', models.CharField(choices=[('W', 'White'), ('B', 'Black')], max_length=150, verbose_name='cor')),
            ],
        ),
    ]
